name: Redeploy Portainer Git Stack
author: Armin Bade
description: Action to redeploy a git stack on an portainer instance

inputs:
  portainerUrl:
    description: 'Portainer URL'
    required: true
  accessToken:
    description: 'Portainer access token'
    required: true
  stackName:
    description: 'Stack ID'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
