name: Portainer Git Stack Redeploy
author: Dzianis Nikifaraŭ
description: Action for request to Portainer API for redeploy stack with pull latest images from GitHub

inputs:
  portainerUrl:
    description: 'Portainer URL'
    required: true
  accessToken:
    description: 'Portainer access token'
    required: true
  stackName:
    description: 'Stack ID'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
